version: '3.8'

services:
     gateway:
       restart: unless-stopped
       build:
         context: ./gateway
         dockerfile: Dockerfile
       volumes:
         - ./gateway:/app
       environment:
         - BOT_PHONE_NUMBER=${BOT_PHONE_NUMBER}
         - WORKER_ENDPOINT=http://worker:3002
         - RELEASE_MODE=${RELEASE_MODE}
       dns:
         - 8.8.8.8
         - 8.8.4.4
       ports:
         - "3001:3001"
       depends_on:
         worker:
           condition: service_healthy
       healthcheck:
         test: ["CMD", "curl", "-f", "http://127.0.0.1:3001/health"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 10s
       networks:
         - whatsapp-bot-network

     worker:
       restart: unless-stopped
       build:
         context: ./worker
         dockerfile: Dockerfile
       volumes:
          - ./worker:/app  
          - ./credentials.json:/app/credentials.json:ro
          - ./credentials_fb.json:/app/credentials_fb.json:ro
          - ./config_price_gold.json:/app/config_price_gold.json:ro
       environment:
          - AI_ENDPOINT=http://ai-service:8000/process_expense
          - AI_IMAGE_ENDPOINT=http://ai-service:8000/process_image_expense
          - AI_ENDPOINT_KEUANGAN=http://ai-service:8000/process_expense_keuangan
          - AI_IMAGE_ENDPOINT_KEUANGAN=http://ai-service:8000/process_image_expense_keuangan
          - AI_ENDPOINT_LM=http://ai-service:8000/process_expense_lm
          - AI_IMAGE_ENDPOINT_LM=http://ai-service:8000/process_image_expense_lm
       ports:
         - "3002:3002"
       depends_on:
         ai-service:
           condition: service_healthy
       healthcheck:
         test: ["CMD", "curl", "-f", "http://127.0.0.1:3002/health"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 10s
       networks:
         - whatsapp-bot-network

     ai-service:
       build:
         context: ./ai-service
         dockerfile: Dockerfile
       volumes:
         - ./ai-service:/app
       environment:
         - GEMINI_API_KEY=${GEMINI_API_KEY}
         - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
       healthcheck:
         test: ["CMD", "curl", "http://localhost:8000/health"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 10s
       networks:
         - whatsapp-bot-network
       ports:
         - "8000:8000"


networks:
     whatsapp-bot-network:
       driver: bridge